### ISSUE TITLE
[multi-site] bug: Does not show related entries that doesn't exist in primary site

### ISSUE THREAD

**Issue by tibbis** [MindseekerMedia/craft-related-elements#5]
Does not show related entries that does now exist in primary site. I suspect that there is a missing `site('*').unique()` in the code for it to display entries outside of primarySite.

**Comment by MindseekerMedia** [comment]
@tibbis That was indeed the case, thank you for pointing it out. Fixed in 1.1.1

**Comment by tibbis** [comment]
still showing the wrong status color, its taking the status of primary site:
<img width="652" alt="image" src="https://github.com/user-attachments/assets/ba7f95fc-c0e1-47b1-8e0e-40e28d20200b" />

**Comment by MindseekerMedia** [comment]
@tibbis Fixed in 1.1.2
